<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-EE6J4Q32" name="Test2" tests="4" failures="1" timestamp="20 Oct 2020 18:10:50 GMT" time="156.012" errors="0">
  <testcase name="byChat" time="4.845" classname="test.ContactUs_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at test.ContactUs_Test.byChat(ContactUs_Test.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- byChat -->
  <testcase name="byemail" time="6.048" classname="test.ContactUs_Test"/>
  <testcase name="byphone" time="8.773" classname="test.ContactUs_Test"/>
  <testcase name="contactUs" time="7.333" classname="test.ContactUs_Test"/>
</testsuite> <!-- Test2 -->
